Replace data type
Since types.Binary was deprecated in sqlalchemy version 0.6 and removed in version 1.4, its usage in lines 26 and 28 produces an "AttributeError: module 'sqlalchemy.types' has no attribute 'Binary'", therefore I changed it to LargeBinary